import { readFile } from "node:fs/promises"
import path from "node:path"
import { expect, test } from "@playwright/test"

const vh = "EVQLVESGGGLVQPGGSLRLSCAASGFTFSDYWMYWVRQAPGKGLEWVSEINTNGLITKYPDSVKGRFTISRDNAKNTLYLQMNSLRPEDTAVYYCARSPSGFNRGQGTLVTVSS"

test("nanobody native preparation, 300 bounded candidates, saved baseline and standalone analysis", async ({ page, context, browser }) => {
  test.setTimeout(120_000)
  const stats = async () => JSON.parse(await readFile(path.join(process.env.BIOMODALS_BROWSER_ROOT!, "stats.json"), "utf8"))
  let setup = ""
  await expect.poll(async () => { setup = (await stats()).nanobody_password_link ?? ""; return setup }).not.toBe("")
  await page.goto(setup)
  await page.getByLabel("New password", { exact: true }).fill("correct horse battery staple")
  await page.getByLabel("Confirm password", { exact: true }).fill("correct horse battery staple")
  await page.getByRole("button", { name: "Set password", exact: true }).click()
  await expect(page).toHaveURL(process.env.BIOMODALS_BROWSER_ORIGIN + "/")
  await page.getByRole("link", { name: /Nanobody humanization/ }).click()
  await expect(page).toHaveURL(/\/tools\/nanobody-humanization$/)
  await page.getByRole("link", { name: "Submit a job", exact: true }).click()
  const originals = Array.from({ length: 100 }, (_, index) => ({ id: `nb_${String(index).padStart(3, "0")}`, vhh: index === 0 ? vh.slice(3) : vh }))
  const before = (await stats()).submit_calls
  await page.getByLabel("CSV file", { exact: true }).setInputFiles({ name: "nanobodies.csv", mimeType: "text/csv", buffer: Buffer.from("id,vhh\n" + originals.map(({ id, vhh }) => `${id},${vhh}`).join("\n")) })
  const preparing = page.waitForResponse((response) => response.url().endsWith("/nanobody-humanization/prepare"))
  await page.getByRole("button", { name: "Prepare sequences", exact: true }).click()
  const preparedResponse = await preparing
  expect(preparedResponse.status()).toBe(200)
  const prepared = await preparedResponse.json()
  expect(prepared.errors).toEqual([])
  expect(prepared.rows).toHaveLength(100)
  expect(prepared.preparation_digest).toMatch(/^[0-9a-f]{64}$/)
  expect(prepared.rows[0].vh).not.toBe(originals[0].vhh)
  expect((await stats()).submit_calls).toBe(before)
  const submitting = page.waitForResponse((response) => response.url().endsWith("/nanobody-humanization/jobs") && response.request().method() === "POST")
  await page.getByRole("button", { name: "Submit humanization", exact: true }).click()
  const submission = await submitting
  expect(submission.status()).toBe(202)
  expect(submission.request().postDataJSON().parents).toEqual(originals)
  expect(submission.request().postDataJSON().preparation_digest).toBe(prepared.preparation_digest)
  const job = await submission.json()
  expect(job.tool).toBe("nanobody_humanization")
  await expect(page).toHaveURL(new RegExp(`/nanobody-humanization/jobs/${job.job_id}$`))
  const stages = page.getByRole("table", { name: "Execution stages", exact: true })
  await expect(stages.locator("tbody tr")).toHaveCount(4)
  await expect(stages).toContainText("AbNatiV2-VHH")
  await expect(stages).toContainText("HuDiff-Nb")
  await expect.poll(async () => (await (await context.request.get(`/api/v1/jobs/${job.job_id}`)).json()).state, { timeout: 30_000 }).toBe("succeeded")
  const reads: string[] = []
  page.on("request", (request) => { if (request.url().includes("/nanobody-humanization/jobs/")) reads.push(request.url()) })
  const firstRead = page.waitForResponse((response) => response.url().includes(`/nanobody-humanization/jobs/${job.job_id}/selection?`))
  await page.getByRole("button", { name: "Refresh", exact: true }).click()
  const firstResponse = await firstRead
  const first = await firstResponse.json()
  expect(first.rows).toHaveLength(50)
  expect(first.total_rows).toBe(300)
  expect(first.columns).toHaveLength(19)
  expect(Object.keys(first.germlines)).toHaveLength(50)
  expect(first.germlines[first.rows[0].candidate_id].assignment).toBeDefined()
  expect(Object.keys(first.nativeness_ranges).sort()).toEqual(["abnativ2_vh_nativeness", "abnativ2_vhh_nativeness"])
  expect(reads.some((url) => url.endsWith("/inputs"))).toBe(false)
  const table = page.getByRole("table", { name: "Nanobody selection.csv, page 1", exact: true })
  await expect(page.getByText("1–50 of 300 rows", { exact: true })).toBeVisible()
  const resultTop = (await page.getByText("Nanobody humanization candidates", { exact: true }).boundingBox())!.y
  expect(resultTop).toBeLessThan((await stages.boundingBox())!.y)
  const headers = await table.locator("thead th > button").allTextContents()
  expect(headers).toContain("vh_pI")
  for (const hidden of first.default_hidden_columns) expect(headers).not.toContain(hidden)
  await table.getByRole("checkbox", { name: /^Select VH from/ }).first().check()
  await page.getByRole("button", { name: "Next page", exact: true }).click()
  await expect(page.getByText("51–100 of 300 rows", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: /^Filter by parent/ }).click()
  await page.getByLabel("Parent", { exact: true }).selectOption(originals[0].id)
  await expect(page.getByText("1–3 of 3 rows", { exact: true })).toBeVisible()
  await expect(table.getByRole("checkbox", { name: /^Select VH from/ }).first()).toBeChecked()
  for (const order of [[1, 2, null], [2, 1, null]]) {
    const sorted = page.waitForResponse((response) => response.url().includes("sort_by=panel_order"))
    await table.getByRole("button", { name: "panel_order", exact: true }).click()
    expect((await (await sorted).json()).rows.map((row: { panel_order: number | null }) => row.panel_order)).toEqual(order)
  }
  const reset = page.waitForResponse((response) => response.url().includes("/selection?") && !response.url().includes("sort_by="))
  await page.getByRole("button", { name: "Restore default order", exact: true }).click()
  expect((await (await reset).json()).rows.map((row: { panel_order: number | null }) => row.panel_order)).toEqual([null, 1, 2])
  const inspecting = page.waitForResponse((response) => response.url().endsWith("/antibody-sequence-analysis/sequence"))
  await table.getByRole("button", { name: /^Inspect VH from/ }).nth(1).click()
  const detailResponse = await inspecting
  expect(detailResponse.status()).toBe(200)
  expect(detailResponse.request().postDataJSON().parental_sequence).toBe(prepared.rows[0].vh)
  const dialog = page.getByRole("dialog")
  await expect(dialog.getByRole("region", { name: "Sequence alignment", exact: true }).locator("tbody th")).toHaveText(["Germline (humanized)", "Humanized relative to its germline", "Humanized", "Humanized relative to parental", "Parental", "Parental relative to its germline", "Germline (parental)"])
  expect(reads.filter((url) => url.endsWith("/inputs"))).toHaveLength(1)
  await dialog.getByRole("button", { name: "Close sequence details", exact: true }).click()
  const csvDownload = page.waitForEvent("download")
  await page.getByRole("button", { name: "Download selection.csv", exact: true }).click()
  const downloadedCsv = await csvDownload
  expect(await downloadedCsv.failure()).toBeNull()
  const csv = await readFile((await downloadedCsv.path())!, "utf8")
  expect(csv.trim().split("\n")).toHaveLength(301)
  expect(csv.split("\n")[0].trim().split(",")).toEqual(first.columns.map((column: { name: string }) => column.name))
  const archiveDownload = page.waitForEvent("download")
  await page.getByRole("button", { name: "Download result", exact: true }).click()
  expect(await (await archiveDownload).failure()).toBeNull()
  expect(reads.filter((url) => url.includes("/selection?")).every((url) => new URL(url).searchParams.get("limit") === "50")).toBe(true)
  const anonymous = await browser.newContext({ baseURL: process.env.BIOMODALS_BROWSER_ORIGIN })
  expect((await anonymous.request.get(`/api/v1/nanobody-humanization/jobs/${job.job_id}/selection`)).status()).toBe(401)
  expect((await anonymous.request.get(`/api/v1/nanobody-humanization/jobs/${job.job_id}/inputs`)).status()).toBe(401)
  await anonymous.close()
  await table.getByRole("checkbox", { name: /^Select VH from/ }).nth(1).check()
  await expect(page.getByRole("region", { name: "Selected antibody chains", exact: true })).toContainText("2 single chains")
  const beforeAnalysis = (await stats()).submit_calls
  const analysis = page.waitForResponse((response) => response.url().endsWith("/antibody-sequence-analysis/analyze"))
  await page.getByRole("button", { name: "Analyze selected sequences", exact: true }).click()
  const analyzed = await analysis
  expect(analyzed.status()).toBe(200)
  const transferredFasta = analyzed.request().postDataJSON().groups[0].fasta as string
  const sequences = transferredFasta.split("\n").filter((line) => line && !line.startsWith(">"))
  expect(sequences).toHaveLength(2)
  expect(sequences[0]).toBe(prepared.rows[0].vh)
  for (const sequence of sequences) expect(sequence).toMatch(/^[A-Z]+$/)
  await expect(page.getByRole("region", { name: "Analysis results: Group 1", exact: true }).locator("tbody tr")).toHaveCount(2)
  expect((await stats()).submit_calls).toBe(beforeAnalysis)
  console.log(`Nanobody offline Result: ${first.rows.length}/${first.total_rows} rows, ${(await firstResponse.body()).length} bytes in first page`)
})
