import { readFile } from "node:fs/promises"
import { randomUUID } from "node:crypto"
import path from "node:path"
import { expect, test, type Locator } from "@playwright/test"
import type { SequenceDetail } from "../src/antibody-analysis"

const vh = "EVQLVESGGGLVQPGGSLRLSCAASGFTFSDYWMYWVRQAPGKGLEWVSEINTNGLITKYPDSVKGRFTISRDNAKNTLYLQMNSLRPEDTAVYYCARSPSGFNRGQGTLVTVSS"

async function expectHallmarkColumns(dialog: Locator, detail: SequenceDetail, rowCount: number) {
  const alignment = dialog.getByRole("region", { name: "Sequence alignment", exact: true })
  const rows = alignment.locator("tbody tr")
  await expect(rows).toHaveCount(rowCount)
  expect(detail.imgt_hallmark_indices).toHaveLength(4)
  const columns = alignment.locator("colgroup col")
  const outlined = await columns.evaluateAll((elements) => elements.flatMap((element, index) => getComputedStyle(element).borderLeftWidth === "1px" ? [index - 1] : []))
  expect(outlined.map((column) => detail.alignment!.input_indices[column])).toEqual(detail.imgt_hallmark_indices)
  const stack = (await alignment.locator("tbody").boundingBox())!
  for (const column of outlined) {
    const outline = columns.nth(column + 1)
    for (const side of ["top", "right", "bottom", "left"]) await expect(outline).toHaveCSS(`border-${side}-width`, "1px")
    const bounds = (await outline.boundingBox())!
    expect(bounds.y).toBeCloseTo(stack.y, 0)
    expect(bounds.height).toBeCloseTo(stack.height, 0)
  }
}

test("nanobody exploration admission, native preparation, 300 bounded candidates and standalone analysis", async ({ page, context, browser }) => {
  test.setTimeout(120_000)
  const stats = async () => JSON.parse(await readFile(path.join(process.env.BIOMODALS_BROWSER_ROOT!, "stats.json"), "utf8"))
  let setup = ""
  await expect.poll(async () => { setup = (await stats()).nanobody_password_link ?? ""; return setup }).not.toBe("")
  await page.goto(setup)
  await page.getByLabel("New password", { exact: true }).fill("correct horse battery staple")
  await page.getByLabel("Confirm password", { exact: true }).fill("correct horse battery staple")
  await page.getByRole("button", { name: "Set password", exact: true }).click()
  await expect(page).toHaveURL(process.env.BIOMODALS_BROWSER_ORIGIN + "/")
  await page.getByRole("link", { name: /Nanobody humanization/ }).click()
  await expect(page).toHaveURL(/\/tools\/nanobody-humanization$/)
  const optionsRead = page.waitForResponse((response) => response.url().endsWith("/nanobody-humanization/options"))
  await page.getByRole("link", { name: "Submit a job", exact: true }).click()
  const options = await (await optionsRead).json()
  expect(options.defaults).toMatchObject({ abnativ2_explore: false, abnativ2_candidate_budget: 1000, root_seed: 0, hudiff_nb_candidate_count: 10 })
  const originals = Array.from({ length: 100 }, (_, index) => ({ id: `nb_${String(index).padStart(3, "0")}`, vhh: index === 0 ? vh.slice(3) : vh }))
  const before = (await stats()).submit_calls
  await page.getByLabel("CSV file", { exact: true }).setInputFiles({ name: "nanobodies.csv", mimeType: "text/csv", buffer: Buffer.from("id,vhh\n" + originals.map(({ id, vhh }) => `${id},${vhh}`).join("\n")) })
  const preparing = page.waitForResponse((response) => response.url().endsWith("/nanobody-humanization/prepare"))
  await page.getByRole("button", { name: "Prepare sequences", exact: true }).click()
  const preparedResponse = await preparing
  expect(preparedResponse.status()).toBe(200)
  const prepared = await preparedResponse.json()
  expect(prepared.errors).toEqual([])
  expect(prepared.rows).toHaveLength(100)
  expect(prepared.preparation_digest).toMatch(/^[0-9a-f]{64}$/)
  expect(prepared.rows[0].vh).not.toBe(originals[0].vhh)
  expect((await stats()).submit_calls).toBe(before)
  const csrf = (await context.cookies()).find((cookie) => cookie.name === "biomodals-csrf")!.value
  const rejected = await context.request.post("/api/v1/nanobody-humanization/jobs", { headers: { Origin: process.env.BIOMODALS_BROWSER_ORIGIN!, "X-CSRF-Token": csrf, "Idempotency-Key": randomUUID() }, data: { display_name: "Offline over-budget check", parents: originals, preparation_digest: prepared.preparation_digest, settings: { ...options.defaults, abnativ2_explore: true } } })
  expect(rejected.status()).toBe(422)
  expect((await rejected.json()).code).toBe("exploration_budget_exceeded")
  expect((await stats()).submit_calls).toBe(before)
  await page.getByText("Advanced settings", { exact: true }).click()
  const submit = page.getByRole("button", { name: "Submit humanization", exact: true })
  await expect(submit).toBeEnabled() // Enhanced mode has no P x B exploration allowance.
  await page.getByRole("checkbox", { name: "Explore more candidates", exact: true }).check()
  await expect(submit).toBeDisabled()
  await page.getByLabel("Candidate evaluations per parent", { exact: true }).fill(String(options.max_exploration_candidates_per_job / originals.length))
  await page.getByRole("checkbox", { name: "Screen by solvent exposure", exact: true }).uncheck()
  await expect(submit).toBeEnabled()
  const submitting = page.waitForResponse((response) => response.url().endsWith("/nanobody-humanization/jobs") && response.request().method() === "POST")
  await submit.click()
  const submission = await submitting
  expect(submission.status()).toBe(202)
  expect(submission.request().postDataJSON().parents).toEqual(originals)
  expect(submission.request().postDataJSON().preparation_digest).toBe(prepared.preparation_digest)
  expect(submission.request().postDataJSON().settings).toMatchObject({ abnativ2_explore: true, abnativ2_candidate_budget: 100, abnativ2_rasa_threshold: 0, root_seed: 0, hudiff_nb_candidate_count: 10 })
  const job = await submission.json()
  const retained = await (await context.request.get(`/api/v1/nanobody-humanization/jobs/${job.job_id}/inputs`)).json()
  expect(retained.settings).toEqual(submission.request().postDataJSON().settings)
  expect(job.tool).toBe("nanobody_humanization")
  await expect(page).toHaveURL(new RegExp(`/nanobody-humanization/jobs/${job.job_id}$`))
  const stages = page.getByRole("table", { name: "Execution stages", exact: true })
  await expect(stages.locator("tbody tr")).toHaveCount(4)
  await expect(stages).toContainText("AbNatiV2-VHH")
  await expect(stages).toContainText("HuDiff-Nb")
  await expect.poll(async () => (await (await context.request.get(`/api/v1/jobs/${job.job_id}`)).json()).state, { timeout: 30_000 }).toBe("succeeded")
  const reads: string[] = []
  page.on("request", (request) => { if (request.url().includes("/nanobody-humanization/jobs/")) reads.push(request.url()) })
  const firstRead = page.waitForResponse((response) => response.url().includes(`/nanobody-humanization/jobs/${job.job_id}/selection?`))
  await page.getByRole("button", { name: "Refresh", exact: true }).click()
  const firstResponse = await firstRead
  const first = await firstResponse.json()
  expect(first.rows).toHaveLength(50)
  expect(first.total_rows).toBe(300)
  expect(first.nonparent_count).toBe(200)
  expect(first.columns).toHaveLength(19)
  expect(Object.keys(first.germlines)).toHaveLength(50)
  expect(first.germlines[first.rows[0].candidate_id].assignment).toBeDefined()
  expect(Object.keys(first.nativeness_ranges).sort()).toEqual(["abnativ2_vh_nativeness", "abnativ2_vhh_nativeness"])
  expect(reads.some((url) => url.endsWith("/inputs"))).toBe(false)
  const table = page.getByRole("table", { name: "Nanobody selection.csv, page 1", exact: true })
  await expect(page.getByText("1–50 of 300 rows", { exact: true })).toBeVisible()
  const resultTop = (await page.getByText("Nanobody humanization candidates", { exact: true }).boundingBox())!.y
  expect(resultTop).toBeLessThan((await stages.boundingBox())!.y)
  const headers = await table.locator("thead th > button").allTextContents()
  expect(headers).toContain("vh_pI")
  for (const hidden of first.default_hidden_columns) expect(headers).not.toContain(hidden)
  await table.getByRole("checkbox", { name: /^Select VH from/ }).first().check()
  await page.getByRole("button", { name: "Next page", exact: true }).click()
  await expect(page.getByText("51–100 of 300 rows", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: /^Filter by parent/ }).click()
  await page.getByLabel("Parent", { exact: true }).selectOption(originals[0].id)
  await expect(page.getByText("1–3 of 3 rows", { exact: true })).toBeVisible()
  await expect(table.getByRole("checkbox", { name: /^Select VH from/ }).first()).toBeChecked()
  for (const order of [[1, 2, null], [2, 1, null]]) {
    const sorted = page.waitForResponse((response) => response.url().includes("sort_by=panel_order"))
    await table.getByRole("button", { name: "panel_order", exact: true }).click()
    expect((await (await sorted).json()).rows.map((row: { panel_order: number | null }) => row.panel_order)).toEqual(order)
  }
  const reset = page.waitForResponse((response) => response.url().includes("/selection?") && !response.url().includes("sort_by="))
  await page.getByRole("button", { name: "Restore default order", exact: true }).click()
  expect((await (await reset).json()).rows.map((row: { panel_order: number | null }) => row.panel_order)).toEqual([null, 1, 2])
  const inspecting = page.waitForResponse((response) => response.url().endsWith("/antibody-sequence-analysis/sequence"))
  await table.getByRole("button", { name: /^Inspect VH from/ }).nth(1).click()
  const detailResponse = await inspecting
  expect(detailResponse.status()).toBe(200)
  const detail: SequenceDetail = await detailResponse.json()
  expect(detailResponse.request().postDataJSON().parental_sequence).toBe(prepared.rows[0].vh)
  const dialog = page.getByRole("dialog")
  await expect(dialog.getByRole("region", { name: "Sequence alignment", exact: true }).locator("tbody th")).toHaveText(["Germline (humanized)", "Humanized relative to its germline", "Humanized", "Humanized relative to parental", "Parental", "Parental relative to its germline", "Germline (parental)"])
  await expectHallmarkColumns(dialog, detail, 7)
  for (const scheme of ["kabat", "chothia", "martin", "aho"]) {
    const changed = page.waitForResponse((response) => response.url().endsWith("/antibody-sequence-analysis/sequence") && response.request().postDataJSON().scheme === scheme)
    await dialog.getByLabel("Numbering scheme").selectOption(scheme)
    const mapped: SequenceDetail = await (await changed).json()
    expect(mapped.imgt_hallmark_indices).toEqual(detail.imgt_hallmark_indices)
    await expectHallmarkColumns(dialog, mapped, 7)
  }
  await dialog.screenshot({ path: test.info().outputPath("nanobody-four-row-hallmarks.png") })
  const missingParentalGermline: SequenceDetail = { ...detail, parental_germlines: [], parental_germline_error: "Parental numbering unavailable", alignment: { ...detail.alignment!, parental_germline: null, parental_germline_diffs: null } }
  await page.route("**/antibody-sequence-analysis/sequence", (route) => route.fulfill({ json: missingParentalGermline }), { times: 1 })
  await dialog.getByLabel("Numbering scheme").selectOption("imgt")
  await expect(dialog.getByText("Not available", { exact: true })).toBeVisible()
  await expectHallmarkColumns(dialog, missingParentalGermline, 6)
  await expect(dialog.locator("tbody tr").last().locator("td")).toHaveCount(detail.alignment!.input.length)
  expect(reads.filter((url) => url.endsWith("/inputs"))).toHaveLength(1)
  await dialog.getByRole("button", { name: "Close sequence details", exact: true }).click()
  const csvDownload = page.waitForEvent("download")
  await page.getByRole("button", { name: "Download selection.csv", exact: true }).click()
  const downloadedCsv = await csvDownload
  expect(await downloadedCsv.failure()).toBeNull()
  const csv = await readFile((await downloadedCsv.path())!, "utf8")
  expect(csv.trim().split("\n")).toHaveLength(301)
  expect(csv.split("\n")[0].trim().split(",")).toEqual(first.columns.map((column: { name: string }) => column.name))
  const archiveDownload = page.waitForEvent("download")
  await page.getByRole("button", { name: "Download result", exact: true }).click()
  expect(await (await archiveDownload).failure()).toBeNull()
  expect(reads.filter((url) => url.includes("/selection?")).every((url) => new URL(url).searchParams.get("limit") === "50")).toBe(true)
  const anonymous = await browser.newContext({ baseURL: process.env.BIOMODALS_BROWSER_ORIGIN })
  expect((await anonymous.request.get(`/api/v1/nanobody-humanization/jobs/${job.job_id}/selection`)).status()).toBe(401)
  expect((await anonymous.request.get(`/api/v1/nanobody-humanization/jobs/${job.job_id}/inputs`)).status()).toBe(401)
  await anonymous.close()
  await table.getByRole("checkbox", { name: /^Select VH from/ }).nth(1).check()
  await expect(page.getByRole("region", { name: "Selected antibody chains", exact: true })).toContainText("2 single chains")
  const beforeAnalysis = (await stats()).submit_calls
  const analysis = page.waitForResponse((response) => response.url().endsWith("/antibody-sequence-analysis/analyze"))
  await page.getByRole("button", { name: "Analyze selected sequences", exact: true }).click()
  const analyzed = await analysis
  expect(analyzed.status()).toBe(200)
  const transferredFasta = analyzed.request().postDataJSON().groups[0].fasta as string
  const sequences = transferredFasta.split("\n").filter((line) => line && !line.startsWith(">"))
  expect(sequences).toHaveLength(2)
  expect(sequences[0]).toBe(prepared.rows[0].vh)
  for (const sequence of sequences) expect(sequence).toMatch(/^[A-Z]+$/)
  const local = page.getByRole("region", { name: "Analysis results: Group 1", exact: true })
  await expect(local.locator("tbody tr")).toHaveCount(2)
  await expect(page.getByRole("button", { name: "Columns", exact: true })).toHaveText("Columns (9/15)")
  await expect(local.getByRole("columnheader", { name: /^VL / })).toHaveCount(0)
  const localCsv = page.waitForEvent("download")
  await local.getByRole("button", { name: "Download CSV", exact: true }).click()
  expect(await readFile((await (await localCsv).path())!, "utf8")).toContain('"vl_pi"')
  const localInspect = page.waitForResponse((response) => response.url().endsWith("/antibody-sequence-analysis/sequence"))
  await local.getByRole("button", { name: "VH", exact: true }).first().click()
  const standalone: SequenceDetail = await (await localInspect).json()
  await expectHallmarkColumns(dialog, standalone, 3)
  for (const scheme of ["kabat", "chothia", "martin", "aho"]) {
    const changed = page.waitForResponse((response) => response.url().endsWith("/antibody-sequence-analysis/sequence") && response.request().postDataJSON().scheme === scheme)
    await dialog.getByLabel("Numbering scheme").selectOption(scheme)
    const mapped: SequenceDetail = await (await changed).json()
    expect(mapped.imgt_hallmark_indices).toEqual(standalone.imgt_hallmark_indices)
    await expectHallmarkColumns(dialog, mapped, 3)
  }
  await dialog.screenshot({ path: test.info().outputPath("nanobody-two-row-hallmarks.png") })
  await dialog.getByRole("button", { name: "Close sequence details", exact: true }).click()
  await page.getByRole("button", { name: "Load example sequences", exact: true }).click()
  await page.getByRole("button", { name: "Analyze sequences", exact: true }).click()
  await expect(local.getByRole("columnheader", { name: /^VL / })).toHaveCount(6)
  await page.getByLabel("Group 1 FASTA", { exact: true }).fill(transferredFasta)
  await page.getByRole("button", { name: "Analyze sequences", exact: true }).click()
  await expect(local.getByRole("columnheader", { name: /^VL / })).toHaveCount(0)
  await page.getByRole("button", { name: "Columns", exact: true }).click()
  await page.getByRole("menuitemcheckbox", { name: "VL pI", exact: true }).click()
  await page.keyboard.press("Escape")
  await expect(local.getByRole("columnheader", { name: "VL pI", exact: true })).toBeVisible()
  expect((await stats()).submit_calls).toBe(beforeAnalysis)
  console.log(`Nanobody offline Result: ${first.rows.length}/${first.total_rows} rows, ${(await firstResponse.body()).length} bytes in first page`)
})
