/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Login */
        readonly post: operations["login_api_v1_auth_login_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Logout */
        readonly post: operations["logout_api_v1_auth_logout_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Me */
        readonly get: operations["me_api_v1_auth_me_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/set-password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Set Password */
        readonly post: operations["set_password_api_v1_auth_set_password_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/gromacs/jobs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Submit Job */
        readonly post: operations["submit_job_api_v1_gromacs_jobs_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/jobs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Jobs */
        readonly get: operations["list_jobs_api_v1_jobs_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/jobs/{job_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Inspect Job */
        readonly get: operations["inspect_job_api_v1_jobs__job_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/jobs/{job_id}/cancel": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Cancel Job */
        readonly post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/jobs/{job_id}/download": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Download Job */
        readonly get: operations["download_job_api_v1_jobs__job_id__download_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_submit_job_api_v1_gromacs_jobs_post */
        readonly Body_submit_job_api_v1_gromacs_jobs_post: {
            /**
             * Cpu Only
             * @default false
             */
            readonly cpu_only: boolean;
            /** Display Name */
            readonly display_name?: string | null;
            /**
             * Pdb
             * @description Input PDB structure
             */
            readonly pdb: string;
            /**
             * Run Pdbfixer
             * @default false
             */
            readonly run_pdbfixer: boolean;
            /**
             * Simulation Time Ns
             * @default 5
             */
            readonly simulation_time_ns: number;
        };
        /**
         * ComputeUnavailableResponse
         * @description Remote compute could not accept the durable Job.
         */
        readonly ComputeUnavailableResponse: {
            /**
             * Code
             * @constant
             */
            readonly code: "compute_unavailable";
            /** Detail */
            readonly detail: string;
        };
        /**
         * ErrorResponse
         * @description Stable JSON error response.
         */
        readonly ErrorResponse: {
            /** Detail */
            readonly detail: string;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * JobNotCancellableResponse
         * @description Cancellation raced with a state that no longer accepts it.
         */
        readonly JobNotCancellableResponse: {
            /**
             * Code
             * @constant
             */
            readonly code: "job_not_cancellable";
            /** Detail */
            readonly detail: string;
        };
        /**
         * JobState
         * @description Durable provider-neutral job states.
         * @enum {string}
         */
        readonly JobState: "queued" | "running" | "finalizing" | "cancel_requested" | "succeeded" | "partial" | "failed" | "cancelled";
        /**
         * JobView
         * @description Provider-neutral job details returned to a submitter.
         */
        readonly JobView: {
            /** Completed At */
            readonly completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Display Name */
            readonly display_name: string;
            /** Download Url */
            readonly download_url?: string | null;
            /** Error Code */
            readonly error_code?: ("compute_failed" | "result_invalid" | "result_unavailable") | null;
            /** Error Message */
            readonly error_message?: string | null;
            /** Job Id */
            readonly job_id: string;
            readonly state: components["schemas"]["JobState"];
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
            /** Warnings */
            readonly warnings?: readonly string[];
            /** Workload */
            readonly workload: string;
        };
        /**
         * LoginRequest
         * @description Credentials submitted only by the browser login form.
         */
        readonly LoginRequest: {
            /** Email */
            readonly email: string;
            /** Password */
            readonly password: string;
        };
        /**
         * MutationForbiddenResponse
         * @description Unsafe request rejected for origin or CSRF state.
         */
        readonly MutationForbiddenResponse: {
            /**
             * Code
             * @enum {string}
             */
            readonly code: "csrf_invalid" | "origin_not_allowed";
            /** Detail */
            readonly detail: string;
        };
        /**
         * OriginErrorResponse
         * @description Browser origin rejected before an unsafe request.
         */
        readonly OriginErrorResponse: {
            /**
             * Code
             * @constant
             */
            readonly code: "origin_not_allowed";
            /** Detail */
            readonly detail: string;
        };
        /**
         * PasswordErrorResponse
         * @description Password Setup errors with distinct recovery behavior.
         */
        readonly PasswordErrorResponse: {
            /**
             * Code
             * @enum {string}
             */
            readonly code: "password_link_invalid" | "password_policy_rejected";
            /** Detail */
            readonly detail: string;
        };
        /**
         * PayloadTooLargeResponse
         * @description Submission exceeded the configured request boundary.
         */
        readonly PayloadTooLargeResponse: {
            /**
             * Code
             * @constant
             */
            readonly code: "payload_too_large";
            /** Detail */
            readonly detail: string;
        };
        /**
         * PdbInvalidResponse
         * @description Semantic PDB validation failure.
         */
        readonly PdbInvalidResponse: {
            /**
             * Code
             * @constant
             */
            readonly code: "pdb_invalid";
            /** Detail */
            readonly detail: string;
        };
        /**
         * PrincipalView
         * @description The small identity document needed by the separate frontend.
         */
        readonly PrincipalView: {
            /** Display Name */
            readonly display_name: string;
            /** Email */
            readonly email: string;
            /**
             * User Id
             * Format: uuid
             */
            readonly user_id: string;
        };
        /**
         * SetPasswordRequest
         * @description One-time password setup or reset submission.
         */
        readonly SetPasswordRequest: {
            /** Password */
            readonly password: string;
            /** Token */
            readonly token: string;
        };
        /**
         * SubmissionConflictResponse
         * @description Submission conflicts with idempotency or active-job state.
         */
        readonly SubmissionConflictResponse: {
            /**
             * Code
             * @enum {string}
             */
            readonly code: "idempotency_conflict" | "active_job_limit_reached";
            /** Detail */
            readonly detail: string;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly login_api_v1_auth_login_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LoginRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    /** @description Sets the HttpOnly session cookie and the readable `biomodals-csrf` cookie used as `X-CSRF-Token`. */
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PrincipalView"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OriginErrorResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly logout_api_v1_auth_logout_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required for authenticated mutations. Copy the value of the `biomodals-csrf` cookie set by a successful login or Password Setup. */
                readonly "X-CSRF-Token": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MutationForbiddenResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly me_api_v1_auth_me_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PrincipalView"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly set_password_api_v1_auth_set_password_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    /** @description Sets the HttpOnly session cookie and the readable `biomodals-csrf` cookie used as `X-CSRF-Token`. */
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PrincipalView"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PasswordErrorResponse"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OriginErrorResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly submit_job_api_v1_gromacs_jobs_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "Idempotency-Key": string;
                /** @description Required for authenticated mutations. Copy the value of the `biomodals-csrf` cookie set by a successful login or Password Setup. */
                readonly "X-CSRF-Token": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": components["schemas"]["Body_submit_job_api_v1_gromacs_jobs_post"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PdbInvalidResponse"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MutationForbiddenResponse"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SubmissionConflictResponse"];
                };
            };
            /** @description Content Too Large */
            readonly 413: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PayloadTooLargeResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ComputeUnavailableResponse"];
                };
            };
        };
    };
    readonly list_jobs_api_v1_jobs_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["JobView"][];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly inspect_job_api_v1_jobs__job_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly job_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly cancel_job_api_v1_jobs__job_id__cancel_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required for authenticated mutations. Copy the value of the `biomodals-csrf` cookie set by a successful login or Password Setup. */
                readonly "X-CSRF-Token": string;
            };
            readonly path: {
                readonly job_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MutationForbiddenResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobNotCancellableResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly download_job_api_v1_jobs__job_id__download_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly job_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Complete ZIP result archive. */
            readonly 200: {
                headers: {
                    /** @description Browser attachment using the server-provided result filename. */
                    readonly "Content-Disposition"?: string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/zip": string;
                };
            };
            /** @description Requested byte range of the ZIP result archive. */
            readonly 206: {
                headers: {
                    /** @description Browser attachment using the server-provided result filename. */
                    readonly "Content-Disposition"?: string;
                    /** @description Byte range returned from the complete archive. */
                    readonly "Content-Range"?: string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/zip": string;
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
